version: "3"
services:
  db:
    image: mysql:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --init-connect='SET NAMES UTF8; SET CHARACTER SET utf8mb4;'
    container_name: docker-for-rails-db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  web:
    build: .
    tty: true
    container_name: docker-for-rails-web
    environment:
      RAILS_ENV: development
      BUNDLE_PATH: /usr/local/bundle
    ports:
      - "8000:3000"
    volumes:
      - ".:/docker-for-rails"
      - /docker-for-rails/node_modules/
      - /docker-for-rails/tmp/
      - gem_cache:/usr/local/bundle:cached
    depends_on:
      - db
volumes:
  gem_cache:
  node_modules:
  db_data:
    driver: local
